import './globals.css';
import type { Metadata } from 'next';
import { AuthProvider, ThemeProvider } from '@/components/primitives/Provider';
import { ReactNode } from 'react';
import Navigation from '@/components/primitives/Navigation';
import Footer from '@/components/primitives/Footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

// to be typed as RootLayoutProps
export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<>
			<html lang="en" suppressHydrationWarning>
				<head />
				<AuthProvider>
					<body>
						<ThemeProvider attribute="class" defaultTheme="light">
							<main className="flex flex-col min-h-screen w-full h-full">
								<Navigation />
								{children}
								<Footer />
							</main>
						</ThemeProvider>
					</body>
				</AuthProvider>
			</html>
		</>
	);
}
